apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: my-app
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: my-app
      component: backend
  template:
    metadata:
      labels:
        app: my-app
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            {{- range .Values.backend.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: my-app
    component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}
