image:
  repository: 551642657440.dkr.ecr.us-east-1.amazonaws.com/awshelm
  tag: "{{ .Values.buildNumber }}"  # Replaced dynamically in Jenkins

backend:
  replicaCount: 2
  image:
    repository: "{{ .Values.image.repository }}-backend"
    tag: "{{ .Values.image.tag }}"
    pullPolicy: Always
  service:
    name: backend
    type: ClusterIP
    port: 8080
  env:
    - name: DATABASE_URL
      value: "jdbc:mysql://{{ .Values.database.host }}:3306/book-rds"
    - name: DATABASE_USERNAME
      value: "{{ .Values.database.username }}"
    - name: DATABASE_PASSWORD
      value: "{{ .Values.database.password }}"

frontend:
  replicaCount: 2
  image:
    repository: "{{ .Values.image.repository }}-frontend"
    tag: "{{ .Values.image.tag }}"
    pullPolicy: Always
  service:
    name: frontend
    type: ClusterIP
    port: 80

database:
  host: ""
  username: ""
  password: ""

buildNumber: "latest"
